apiVersion: v1
kind: Service
metadata:
  name: user-data-service
spec:
  selector:
    app: user-data-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-data-service
  template:
    metadata:
      labels:
        app: user-data-service
    spec:
      containers:
        - name: user-data-service
          image: mak1995/user-data-service:latest
          ports:
            - containerPort: 8082
